name: englishkey
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^10.2.0
  filesystem_picker: ^4.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_pdfview: ^1.4.1+1
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
