name: englishkey
description: "A Flutter app for learning English with fun and engaging features."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  confetti: ^0.8.0
  file_picker: ^10.2.0
  filesystem_picker: ^4.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_pdfview: ^1.4.1+1
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  wakelock_plus: ^1.3.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#303030"
  image: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
