// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGQF8ZUgIs9OTpi8C0Qcs6t8GItc-MEFE',
    appId: '1:178900074133:web:38982b50bc3f360731e59c',
    messagingSenderId: '178900074133',
    projectId: 'english-key-firebase',
    authDomain: 'english-key-firebase.firebaseapp.com',
    storageBucket: 'english-key-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvNiOo6aukebnFxPSQMJpFYnYeAQMavyY',
    appId: '1:178900074133:android:c0098953da918ea531e59c',
    messagingSenderId: '178900074133',
    projectId: 'english-key-firebase',
    storageBucket: 'english-key-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYj1UU44rszR8PmBIR944YN1uLQjK6J5s',
    appId: '1:178900074133:ios:a58e2333e5c2108e31e59c',
    messagingSenderId: '178900074133',
    projectId: 'english-key-firebase',
    storageBucket: 'english-key-firebase.firebasestorage.app',
    iosBundleId: 'com.example.englishkey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYj1UU44rszR8PmBIR944YN1uLQjK6J5s',
    appId: '1:178900074133:ios:a58e2333e5c2108e31e59c',
    messagingSenderId: '178900074133',
    projectId: 'english-key-firebase',
    storageBucket: 'english-key-firebase.firebasestorage.app',
    iosBundleId: 'com.example.englishkey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGQF8ZUgIs9OTpi8C0Qcs6t8GItc-MEFE',
    appId: '1:178900074133:web:f210177ba416949731e59c',
    messagingSenderId: '178900074133',
    projectId: 'english-key-firebase',
    authDomain: 'english-key-firebase.firebaseapp.com',
    storageBucket: 'english-key-firebase.firebasestorage.app',
  );
}
